### ISSUE TITLE
Not support Xcode6.1.1

### ISSUE THREAD

**Issue by alexlee002** [limejelly/Backlight-for-XCode#22]
as title.

**Comment by limejelly** [comment]
Will close since no news about this. Can somebody confirm it?

**Comment by PaNaVTEC** [comment]
Works for me Version 6.1.1 (6A2008a) + 10.10.1

**Comment by Rameshv** [comment]
i checked in `6.1.1 (6A2008a)`, it didnt work immediately after installing and restarting the xcode. you will have to manually goto `Edit->Backlight` and select the option you want. It works fine after that
