### ISSUE TITLE
Uninstall instructions?

### ISSUE THREAD

**Issue by samkelleher** [limejelly/Backlight-for-XCode#26]
Building the project magically adds it to XCode, how to remove it?

**Comment by limejelly** [comment]
Try to change some "Deployment" settings, under "Build settings" section in plugin target.

**Comment by samkelleher** [comment]
Magic, just where you said it was. Reveals the installation directory as `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins`. Delete the generated pluginfile and menu option goes away.
