### ISSUE TITLE
Backlight multiple lines if 2 editors in focus

### ISSUE THREAD

**Issue by PaNaVTEC** [limejelly/Backlight-for-XCode#27]
To test it:
- Open the assistant editor, so now you have 2 editors.
- Backlight one line on some of two editors
- Click other line in the other editor
- Click other line in the first editor

Now you have multiple backlighted lines

**Comment by tyeen** [comment]
This is a bug introduced by the Underneath mode. It won't happen in Overlay mode.
Sorry for the inconvenience. I've submitted a patch.
